import localFont from "next/font/local";
import "./globals.css";
import HeaderFirstTop from "./components/HeaderFirstTop";

// icons
import { config } from "@fortawesome/fontawesome-svg-core";
import '@fortawesome/fontawesome-svg-core/styles.css';
import HeaderSecondTop from "./components/HeaderSecondTop";
import Navbar from "./components/Navbar";
import CartProvider from "./context/CartProvider";
import FavouriteProvider from "./context/FavouriteProvider";
import Footer from "./components/Footer";
config.autoAddCss = false;

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>e-commerce</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FavouriteProvider>
          <CartProvider>
            <div className="relative">
              <HeaderFirstTop/>
              <HeaderSecondTop/>
              <Navbar/>
            </div>
            {children}
            <Footer/>
          </CartProvider>
        </FavouriteProvider>
      </body>
    </html>
  );
}
